[DEFAULT]
Executable = File.exe
GameVersion = Pirated # Original | Pirated
GameVaultGameID = -1 # (this is automatically retrieved) To launch the game through gamevault protocol
SteamAppID = -1 # To launch the game through steam protocol
DontAskAgain = False
NoOriginal = False

[CRACK]
Type = OnlineFix # Goldberg | OnlineFix | RUNE | Other | NoSetup | Goldberg_Old
SetupComplete = False
NoSetup = False

[SETUP]
PathMoveLinkingComplete = False
FileEditsComplete = False
FileEdits = """
"""

# C:\File\path\here.ini ;; 
# Message: ;; 
# Short Instruction ;; 
# Long Instruction--
# --message here. ;;
# None ;;  # Default Value
# uuid ;;  # Key Action
# uuid ;;  # Validator
# User ;;  # Section
# UUID     # Key
# ,,
# C:\File\path\here2.ini ;; 
# ...

PathMoveLinking = """
"""

# Source | New Source Location | Type (Directory | File)
# keywords:
# {game_name} = Name of game folder
# {game_persistent_data_path} - PATH to persistent data including game's directory
# ex.
# .\source dir ;; C:\Path\To\new source path ;; Directory,,
# C:\Path\To\Source\source.txt ;; new source location.txt ;; File,,
# saves ;; {game_persistent_data_path}\saves ;; Directory

[OTHER]
NoGameVaultMode = False